name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.12.1
  firebase_crashlytics:
  firebase_analytics: ^11.4.5
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  get:
  http:
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  palette_generator: ^0.3.3+7
  flutter_sslcommerz: ^2.4.4
  qr_flutter: ^4.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/